version: '3.2'

services:
  rgb-node-0:
    container_name: rgb-node-0
    image: lnpbp/rgbd:v0.1.0
    restart: unless-stopped
    entrypoint: "rgbd -vvvv"
  rgb-node-1:
    container_name: rgb-node-1
    image: lnpbp/rgbd:v0.1.0
    restart: unless-stopped
    entrypoint: "rgbd -vvvv"

